<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-30 at 19:05:22.
 */
class Mageflow_Connect_Model_Api2_Help_Rest_Admin_V1Test extends PHPUnit_Framework_TestCase
{

    /**
     * @var Mageflow_Connect_Model_Api2_Help_Rest_Admin_V1
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Mageflow_Connect_Model_Api2_Help_Rest_Admin_V1;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Mageflow_Connect_Model_Api2_Help_Rest_Admin_V1::_retrieve
     * @todo   Implement test_retrieve().
     */
    public function test_retrieve()
    {
        $this->object->_retrieve();
    }

}
