<?php

/**
 * js.phtml
 *
 * MageFlow Connector Magento extension template file
 * outputs CSS and JavaScript to Magento backend
 *
 * @category   MFX
 * @package    Mageflow_Connect
 * @subpackage Lib
 * @author     Prototypely Ltd, Estonia <info@prototypely.com>
 * @copyright  Copyright © 2017 Prototypely Ltd, Estonia (http://prototypely.com) 
 * @license MIT Copyright (c) 2017 Prototypely Ltd
 * @link       http://mageflow.com/
 */

echo $this->getCssJsHtml();