<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-31 at 06:34:45.
 */
class Mageflow_Connect_Model_ObserverTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Mageflow_Connect_Model_Observer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = Mage::getSingleton('Mageflow_Connect_Model_Observer');
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @covers Mageflow_Connect_Model_Observer::_construct
     */
    public function testObject()
    {
        $this->assertInstanceOf('Mageflow_Connect_Model_Observer', $this->object);
    }

    /**
     * @covers Mageflow_Connect_Model_Observer::collectMemoryUsage
     * @todo   Implement testCollectMemoryUsage().
     */
    public function testCollectMemoryUsage()
    {
        $this->object->collectMemoryUsage();
    }

    /**
     * @covers Mageflow_Connect_Model_Observer::getTypeHelper()
     */
    public function testGetTypeHelper()
    {
        $typeHelper = $this->object->getTypeHelper();
        $this->assertInstanceOf('Mageflow_Connect_Helper_Type', $typeHelper);
    }

    /**
     * @covers Mageflow_Connect_Model_Observer::saveChangesetItem()
     */
    public function testSaveChangesetItem()
    {
        $observer = new Varien_Event_Observer();
        $event = new Varien_Event(array('name' => 'my_custom_event'));
        $observer->setEvent($event);
        $this->object->saveChangesetItem($observer);
    }

    /**
     * @covers Mageflow_Connect_Model_Observer::onMoveCategory()
     */
    public function testOnMoveCategory()
    {
        $observer = new Varien_Event_Observer();
        $event = new Varien_Event(array('name' => 'my_custom_event'));
        $observer->setEvent($event);
        $this->object->onMoveCategory($observer);
    }

    /**
     * @covers Mageflow_Connect_Model_Observer::onModelSaveCommitAfter()
     */
    public function testOnModelSaveCommitAfter()
    {
        $observer = new Varien_Event_Observer();
        $event = new Varien_Event(array('name' => 'my_custom_event'));
        $observer->setEvent($event);
        $this->object->onModelSaveCommitAfter($observer);
    }

    /**
     * @covers Mageflow_Connect_Model_Observer::onBeforeSave()
     */
    public function testOnBeforeSave()
    {
        $observer = new Varien_Event_Observer();
        $event = new Varien_Event(array('name' => 'my_custom_event'));
        $observer->setEvent($event);
        $this->object->onBeforeSave($observer);
    }

    /**
     * @covers Mageflow_Connect_Model_Observer::onControllerActionPredispatch()
     */
    public function testOnControllerActionPredispatch()
    {
        $observer = new Varien_Event_Observer();
        $event = new Varien_Event(array('name' => 'my_custom_event'));
        $observer->setEvent($event);
        $this->object->onControllerActionPredispatch($observer);
    }
}
