<?php

require_once 'Mageflow/Connect/controllers/PushController.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-15 at 19:52:23.
 */
class Mageflow_Connect_MigrateControllerTest extends Zend_Test_PHPUnit_ControllerTestCase
{

    /**
     *
     * @var Zend_Controller_Request_HttpTestCase
     */
    protected $request;

    /**
     *
     * @var Zend_Controller_Response_HttpTestCase
     */
    protected $response;

    /**
     * @var Mageflow_Connect_MigrateController
     */
    protected $controller;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->request = new Zend_Controller_Request_HttpTestCase();
        $this->response = new Zend_Controller_Response_HttpTestCase();
        $this->controller = new Mageflow_Connect_MigrateController($this->request,
            $this->response);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testObject()
    {
        $this->assertInstanceOf('Mageflow_Connect_MigrateController',
            $this->controller);
    }

    /**
     * @covers Mageflow_Connect_MigrateController::_construct
     * @todo   Implement test_construct().
     */
    public function test_construct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Mageflow_Connect_MigrateController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Mageflow_Connect_MigrateController::pushAction
     * @todo   Implement testPushAction().
     */
    public function testPushAction()
    {
        $this->request->setActionName('push');
        $this->request->setControllerName('migrate');

        $response = $this->controller->pushAction();
    }

}
