<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-16 at 21:13:45.
 */
include_once 'Mageflow/Connect/controllers/ConnectController.php';

class Mageflow_Connect_ConnectControllerTest extends Zend_Test_PHPUnit_ControllerTestCase {

	/**
	 * @var Mageflow_Connect_AjaxController
	 */
	protected $controller;

	/**
	 *
	 * @var Zend_Controller_Request_HttpTestCase
	 */
	protected $request;

	/**
	 *
	 * @var Zend_Controller_Response_HttpTestCase
	 */
	protected $response;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->request    = new Zend_Controller_Request_Http();
		$this->response   = new Zend_Controller_Response_Http();
		$this->controller = new Mageflow_Connect_ConnectController( $this->request, $this->response );
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	public function testObject() {
		$this->assertInstanceOf( 'Mageflow_Connect_ConnectController', $this->controller );
	}

	/**
	 * @covers Mageflow_Connect_ConnectController::connect20Action
	 */
	public function testConnect20Action() {
		/**
		 * @var $requestToken Zend_Oauth_Token_Request
		 */
		$requestToken = $this->controller->connect20Action();
		$this->assertTrue( is_string( $requestToken->getToken() ) );
		$this->assertTrue( is_string( $requestToken->getTokenSecret() ) );
		print_r( $requestToken->getToken() );
	}


}
