<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-29 at 17:10:19.
 */
class Mageflow_Connect_Model_Api2_System_Info_Rest_Admin_V1Test extends PHPUnit_Framework_TestCase
{

    /**
     * @var Mageflow_Connect_Model_Api2_System_Info_Rest_Admin_V1
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = Mage::getModel('mageflow_connect/api2_system_info_rest_admin_v1');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testObject()
    {
        $this->assertInstanceOf('Mageflow_Connect_Model_Api2_System_Info_Rest_Admin_V1',
            $this->object);
    }

    /**
     * @covers Mageflow_Connect_Model_Api2_System_Info_Rest_Admin_V1::_retrieve
     * @todo   Implement test_retrieve().
     */
    public function test_retrieve()
    {
        $retval = $this->object->_retrieve();
        $this->assertNotEmpty($retval);
        foreach ( $this->object->getAvailableAttributesFromConfig() as
                $attributeName=>$attributeText )
        {
            $this->assertArrayHasKey($attributeName, $retval);
        }
    }

}
