<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-29 at 19:02:48.
 */
class Mageflow_Connect_Model_System_InfoTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Mageflow_Connect_Model_System_Info
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Mageflow_Connect_Model_System_Info;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Mageflow_Connect_Model_System_Info::getPerformanceHistory
     * @todo   Implement testGetPerformanceHistory().
     */
    public function testGetPerformanceHistory()
    {
        $retval = $this->object->getPerformanceHistory();
        $this->assertNotEmpty($retval);
    }

}
