<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-08-09 at 18:11:13.
 */
class Mageflow_Connect_Helper_DataTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Mageflow_Connect_Helper_Data
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Mageflow_Connect_Helper_Data;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testRandomHash()
    {
        $hash = $this->object->randomHash();
        $this->assertNotEmpty($hash);
        printf("%s\n", $hash);
    }


}
