<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-29 at 18:37:37.
 */
class Mageflow_Connect_Model_System_Info_CpuTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Mageflow_Connect_Model_System_Info_Cpu
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Mageflow_Connect_Model_System_Info_Cpu;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Mageflow_Connect_Model_System_Info_Cpu::getCpuCores
     * @todo   Implement testGetCpuCores().
     */
    public function testGetCpuCores()
    {
        $retval = $this->object->getCpuCores();
        $this->assertGreaterThan(0, $retval);
    }

    /**
     * @covers Mageflow_Connect_Model_System_Info_Cpu::getSystemLoad
     * @todo   Implement testGetCpuLoad().
     */
    public function testGetCpuLoad()
    {
        $retval = $this->object->getSystemLoad();
        $this->assertGreaterThan(0, $retval);
    }

}
