<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-15 at 13:57:43.
 */
require_once 'Mageflow/Connect/controllers/IndexController.php';
class Mageflow_Connect_Block_Adminhtml_Migrate_GridTest extends Zend_Test_PHPUnit_ControllerTestCase
{

    /**
     * @var Mageflow_Connect_Block_Adminhtml_Migrate_Grid
     */
    protected $object;

    /**
     * @var Zend_Test_PHPUnit_ControllerTestCase
     */
    protected $controller;

    /**
     *
     * @var Zend_Controller_Request_HttpTestCase
     */
    protected $request;

    /**
     *
     * @var Zend_Controller_Response_HttpTestCase
     */
    protected $response;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->request = new Zend_Controller_Request_HttpTestCase();
        $this->response = new Zend_Controller_Response_HttpTestCase();

        $this->controler = new Mageflow_Connect_IndexController($this->request, $this->response);
        $this->object = Mage::getBlockSingleton('mageflow_connect/adminhtml_migrate_grid');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testObject(){
        $this->assertInstanceOf('Mageflow_Connect_Block_Adminhtml_Migrate_Grid', $this->object);
    }
    /**
     * @covers Mageflow_Connect_Block_Adminhtml_Migrate_Grid::collectCmsBlocks
     * @todo   Implement testCollectCmsBlocks().
     */
    public function testCollectCmsBlocks()
    {
        $collection = $this->object->collectCmsBlocks();
        $this->assertNotEmpty($collection);
        foreach($collection as $item){
            $this->assertGreaterThan(0, $item->getBlockId());
            print_r($item->getResource()->lookupStoreIds($item->getBlockId()));
        }
    }

    /**
     * @covers Mageflow_Connect_Block_Adminhtml_Migrate_Grid::_prepareMassaction
     * @todo   Implement test_prepareMassaction().
     */
    public function test_prepareMassaction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
